// <auto-generated />
using System;
using CarParking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarParking.Migrations
{
    [DbContext(typeof(CarParkingContext))]
    partial class CarParkingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarParking.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("CarParking.Models.BaiXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AllSlot")
                        .HasColumnType("int");

                    b.Property<string>("NhanVienQL_IDId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RemainingSlot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienQL_IDId");

                    b.ToTable("BaiXe");
                });

            modelBuilder.Entity("CarParking.Models.KhachHang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BaiXe_IdId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("timeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("timeOut")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaiXe_IdId");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("CarParking.Models.NhanVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("dChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserNameId");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("CarParking.Models.BaiXe", b =>
                {
                    b.HasOne("CarParking.Models.NhanVien", "NhanVienQL_ID")
                        .WithMany()
                        .HasForeignKey("NhanVienQL_IDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVienQL_ID");
                });

            modelBuilder.Entity("CarParking.Models.KhachHang", b =>
                {
                    b.HasOne("CarParking.Models.BaiXe", "BaiXe_Id")
                        .WithMany()
                        .HasForeignKey("BaiXe_IdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiXe_Id");
                });

            modelBuilder.Entity("CarParking.Models.NhanVien", b =>
                {
                    b.HasOne("CarParking.Models.Account", "UserName")
                        .WithMany()
                        .HasForeignKey("UserNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserName");
                });
#pragma warning restore 612, 618
        }
    }
}
